### PR TITLE
Quote reserved words only

### PR DESCRIPTION
**Pull request by 0902horn**
Related to #18

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]

**Review by xiangfu0 — APPROVED** [review]
We can do it for now.

I feel we also need to parse the expression to get function/identifier/literal then only put double quotes on identifier

**Comment by 0902horn** [comment]
> We can do it for now.
> 
> I feel we also need to parse the expression to get function/identifier/literal then only put double quotes on identifier

I think you could be right. However according to my local tests using latest Superset, the identifier used in a function is quoted correctly if this PR is applied. I don't really know why (no experiences on sqlalchemy compilation extensions), so I might need more feedback about #18 .

**Comment by 0902horn** [comment]
This PR would be a step forward before we get further feedback.

**Comment by 0902horn** [comment]
This PR would be a step forward before we get further feedback.

**Comment by xiangfu0** [comment]
Thanks for fixing this! 0.3.7 is published.

**Pull request merged**
